### ISSUE TITLE
The name of "Semi open files" are not that visible

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-visualstudio#14]
I don't know how to properly explain this, but when you Ctrl+Click something in Visual Studio, it will be opened but to the right side of the list of open files.

For this type of open files, the tab color will be dark enough to make the filename unreadable.

Here is an example, where the text "EntityMetadata.cs" is unreadable due to the tab color (if you couldn't find it, is to the left of the Solution Explorer at the top).

![image](https://user-images.githubusercontent.com/11861253/136678925-cbf116a6-6881-4ffa-8d94-1c2af99ed349.png)

**Comment by Unthrottled** [comment]
Got it, this is whenever you `Go to Definition` of a library file or something. I'll probably make it the same color as an active tab, because it gets pinned to the right and has a 🔒 symbol on on it. 

Though with Rider, the tab does show up in a different color

![image](https://user-images.githubusercontent.com/15972415/136696528-c99962d1-a8ce-4d7e-9498-b0ffa49e08d1.png)

I'll look into that once I am done with the light themes.
