### ISSUE TITLE
Themes crash visual studio's xaml designer

### ISSUE THREAD

**Issue by avail** [doki-theme/doki-theme-visualstudio#19]
Exception message is `Cannot find resource named 'VS.Cider.InputTextColor'. Resource names are case sensitive.`

To reproduce, make a new wpf project, select the grid in the designer and open it's properties window.
Happens to me on VS22 preview 7

**Comment by Unthrottled** [comment]
Got it, I can replicate the issue. I'll have a fix out later this week. Thanks for bringing this to my attention!

**Comment by Unthrottled** [comment]
Hey! So I think I was able to get all of the colors put in.

I've never done any development using this tool, so I just clicked around a bunch and tried to find where thinks would break. I cloned this repo https://github.com/microsoft/WPF-Samples and just tested stuff.

![image](https://user-images.githubusercontent.com/15972415/140670721-18072459-ad28-4a0c-a2a3-8f889d7bf85e.png)


That being said, if you run into any more issues, please provide a detailed list if steps for replication, because all this is new to me 😄

**Comment by avail** [comment]
Thank you very much! If I do run into any more issues I'll make sure to notify you.
