### ISSUE TITLE
Darkness Dark theme improvements

### ISSUE THREAD

**Issue by ElrohirGT** [doki-theme/doki-theme-visualstudio#23]
Hello! I'm really loving this extension, specifically the darkness theme, today I was using it in some of my personal projects and found that the text color for the commit message is black and illegible, like in the screenshot below.
![image](https://user-images.githubusercontent.com/45268815/140999200-eb009900-2f53-445e-b432-6a18ba246a22.png)
![image](https://user-images.githubusercontent.com/45268815/140999226-c7088ddb-3ab5-4929-81d8-860cff418363.png)
I'm not sure what the property change should be but if I find it, I'll post it below. I'm thinking more of a white color or at least the gray color when the text box is empty would be neat.

**Comment by Unthrottled** [comment]
Hey! This looks like visual studio and not visual studio code.

This issue is present probably for all themes, not just Darkness.

![Jahy](https://user-images.githubusercontent.com/15972415/141030692-70da773f-76ee-48e4-a524-dbdfcbcb84a0.png)

I'll dig through the 2000+ color properties and find the needle in the haystack,  
Will change it to make it usable. Thanks for reporting!

**Comment by ElrohirGT** [comment]
Thank you!

**Comment by Unthrottled** [comment]
Happy to help, and sorry about overlooking that (I don't use visual studio very much, if that is telling).

Anyways, 2.1.1 is published to the marketplace now.

**Comment by ElrohirGT** [comment]
No problem, if I find some other problems with the themes I'll open a new issue to let you know! This extension is really cool.
