### ISSUE TITLE
Debugging is confusing due to a lot of info being white

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-visualstudio#31]
*This was only tested with the Cinnamon theme, I'm not sure if it applies to the other themes*

I just recently noticed that is very problematic to debug stuff in VS with the theme applied, as it makes a lot of icons and information white instead of their respective colors. For Example:

* White instead of Red
  * Stop Button
  * Hot Reload Button
  * Breakpoints
  * Breakpoint Hit
* White instead of Green
  * Continue/Start Button

The ones listed above are very important, as the color kinda determines what they do when taking a quick look (green for start, red for stop or pause).

![image](https://user-images.githubusercontent.com/11861253/144508266-728913ff-c6bc-4855-bcc2-8230607a1d8b.png)
![image](https://user-images.githubusercontent.com/11861253/144508545-b57dfd8e-4b97-4e28-a634-a6a5f81c1016.png)

**Comment by Unthrottled** [comment]
🤔 Hmm, I didn't explicitly do that.

I will turn the stop & hot reload back to the red, but the rest of the stuff mentioned, I'm going to make theme accent color (Cinnamon's accent color is the bright green used in the Tab & scroll bar tab, and other places).

I'm also going to look into making the breakpoint hit more visible for all themes.

Will eventually swing around and get to updating this plugin, unless you are dying and need this sooner.

**Comment by justalemon** [comment]
> I will turn the stop & hot reload back to the red, but the rest of the stuff mentioned, I'm going to make theme accent color (Cinnamon's accent color is the bright green used in the Tab & scroll bar tab, and other places).

Yeah, that sounds like the most reasonable way to do it.

> I'm also going to look into making the breakpoint hit more visible for all themes.

I feel that the basic red is good for most themes, except those that use red as a highlight color (Yumeko for example, a lighter red would probably help).

> Will eventually swing around and get to updating this plugin, unless you are dying and need this sooner.

Well, I kinda had to go back to regular VS 2022 Dark so... yeah.

**Comment by Unthrottled** [comment]
@justalemon 

I looked into this and turns out I have no control over what the icon's look like.

> In order to make icons appear with the correct contrast ratio in the Visual Studio dark theme, an inversion is applied programmatically. The colors in this guide have been chosen in part so that they invert correctly. Restrict your use of color to this palette, or you will get unpredictable results when the inversion is applied.

[ref](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2022#color-inversion-for-dark-themes)

> In the RTM version, we dynamically adjust the icons according to the theme, resulting in icons that are cleaner and better matched to the theme and background color. At runtime, we modify the luminosity of the raster images to match the outline of the icon with the background on which it is drawn and to make the fill and accent colors stand out effectively. 

[ref](https://devblogs.microsoft.com/visualstudio/visual-studio-dark-theme/)

So the only way for me to fix this is to update Cinnamon's current color palette, such that the icons will be less dumb. I am _not_ going to do that, because I like the way Cinnamon is right now.

Since this issue is killing you, I will give you some options: 

- Abandon the Cinnamon Doki Theme and switch to another theme. Supplementing the asset feature with [Claudia IDE](https://github.com/buchizo/ClaudiaIDE). I could add a custom sticker option that stays for non-doki themes, so you can still have a cinnamon sticker.

- Switch to the paid JetBrains [Rider](https://www.jetbrains.com/rider/) IDE, then you can use the more polished Doki Theme Jetbrains plugin. Which doesn't have this issue.
![image](https://user-images.githubusercontent.com/15972415/144761485-3e61adfe-53ab-46c1-baf5-d09e33d9a5f0.png)

- Deal with it. 😄 

--- 

Those are the current options I can think of, sorry for not being able to fix this issue. 
It also looks like this affects Tohru, Maple, Nakano Nino, Emilia Dark,  Konata, & Yuri Dark.

**Comment by justalemon** [comment]
When an unpolished theme system messes everything up...

Looks like ill have to deal with it for now lol
